feat: added support to enable the secrets manager public cert engine
terraform-ibm-modules/stack-ibm-core-security-services pull request #100
Opened 2024-07-30 09:01 UTC by iamar7

### Description

Resolves: 9714(internal)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-08-02 11:16 UTC, iamar7 commented
/run pipeline

2024-08-02 11:22 UTC, iamar7 commented
/run pipeline

2024-08-04 22:38 UTC, iamar7 commented
/run pipeline

2024-08-06 14:08 UTC, iamar7 commented
/run pipeline

2024-08-07 07:54 UTC, Ak-sky commented
/run pipeline

2024-08-07 09:36 UTC, iamar7 commented
```
│   [ERROR] Error when creating resource instance: Please contact the Service Provider for this error. [422, Unprocessable Entity] This account reached the number of Trial plan instances that are allowed. To proceed, you must select the Standard plan or delete an existing Trial instance. If you delete the Trial plan instance, you must also delete its reclamation by using the IBM Cloud CLI. Learn more: https://ibm.biz/BdPa49 with resp code: {
│       "StatusCode": 422,
│       "Headers": {
│           "Cache-Control": [
│               "max-age=0, no-cache, no-store"
│           ],
│           "Content-Length": [
│               "851"
│           ],
│           "Content-Type": [
│               "application/json; charset=utf-8"
│           ],
│           "Date": [
│               "Wed, 07 Aug 2024 08:09:43 GMT"
│           ],
│           "Expires": [
│               "Wed, 07 Aug 2024 08:09:43 GMT"
│           ],
│           "Pragma": [
│               "no-cache"
│           ],
│           "Request-Id": [
│               "bss-56be5a8254bee3cc"
│           ],
│           "Retry-After": [
│               "0"
│           ],
│           "Server": [
│               "istio-envoy"
│           ],
│           "Set-Cookie": [
│               "ak_bmsc=2761CDC426D933285F22790894DF93D2~000000000000000000000000000000~YAAQrSTDF5s62RWRAQAAkgPjKxh7qkPJMxD6TNDGFjlDyxvYDA85bVkl8MhkJDCjYrWba1q2FjCPZ950tSsLA9kFJ95pYtkQKt9opXa/gKO3aDQ/gcJfbQZ92tvRs3Cdem9ddPYbTsDFXKCxMGAUvSWMAatIJcyNYUqctuKImUI/DhbWAWp+VeEOIARqwQu9wg1Qxjbya3OWWrW7dCG/vE33eeXmBecfhZH59sD+i3F4lP+h4LHYTovg/ChItuVbb18T2EqdbqYwmlfZDr73z54r0RmmMjdb57F14LJgeql9dJd8f/Ie2WMujjfpaLqq7hgUUOUmECcrxyS06ibVlNo0uxE5BKQ3MsiGA6IB9MP3MbKE6cDCQir4sgOvIMUSaLzcJvg7cBqw9wpHPQ==; Domain=.cloud.ibm.com; Path=/; Expires=Wed, 07 Aug 2024 10:09:41 GMT; Max-Age=7198"
│           ],
│           "Strict-Transport-Security": [
│               "max-age=31536000;includeSubDomains"
│           ],
│           "Transaction-Id": [
│               "bss-c05d19b55b1820e9"
│           ],
│           "X-Content-Type-Options": [
│               "nosniff"
│           ],
│           "X-Correlation-Id": [
│               "bss-c05d19b55b1820e9"
│           ],
│           "X-Envoy-Upstream-Service-Time": [
│               "1770"
│           ],
│           "X-Op-Completion-Time": [
│               ""
│           ],
│           "X-Ratelimit-Limit": [
│               "100"
│           ],
│           "X-Ratelimit-Remaining": [
│               "98"
│           ],
│           "X-Ratelimit-Reset": [
│               "0"
│           ]
│       },
│       "Result": {
│           "details": "{\"error\":\"Bad Request\",\"description\":\"This account reached the number of Trial plan instances that are allowed. To proceed, you must select the Standard plan or delete an existing Trial instance. If you delete the Trial plan instance, you must also delete its reclamation by using the IBM Cloud CLI. Learn more: [https://ibm.biz/BdPa49\](https://ibm.biz/BdPa49/)"}",
│           "error_code": "RC-ServiceBrokerErrorResponse",
│           "message": "Please contact the Service Provider for this error. [422, Unprocessable Entity] This account reached the number of Trial plan instances that are allowed. To proceed, you must select the Standard plan or delete an existing Trial instance. If you delete the Trial plan instance, you must also delete its reclamation by using the IBM Cloud CLI. Learn more: https://ibm.biz/BdPa49",
│           "status_code": 422,
│           "transaction_id": "bss-c05d19b55b1820e9"
│       },
│       "RawResult": null
│   }
│ severity: error
│ resource: ibm_resource_instance
│ operation: create
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.68.0
│ ---
│ 
╵}
```

2024-08-07 09:40 UTC, iamar7 commented
Will be updating the SM to create `standard` plan instead of `trial` since the single account can have only one trial plan.


![image](https://github.com/user-attachments/assets/e51ae173-7024-40ae-9354-4828e6d55b4a)

2024-08-07 09:43 UTC, iamar7 commented
/run pipeline

2024-08-07 09:55 UTC, iamar7 commented
/run pipeline

2024-08-07 12:28 UTC, iamar7 commented
/run pipeline

2024-08-07 13:59 UTC, iamar7 commented
/run pipeline

2024-08-12 07:58 UTC, iamar7 commented
/run pipeline

2024-08-12 09:29 UTC, iamar7 commented
Getting this error during the pipeline run of the `TestProjectsExistingResourcesTest` - 
 ```
Error: [0m Error: [ERROR] Error Deleting resource group: Resource groups with active instances can't be deleted. Use the CLI command "ibmcloud resource service-instances --type all -g <resource-group>" to check for remaining instances, then delete the instances and try again. with response code  {
│     "StatusCode": 500,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store"
│         ],
│         "Content-Length": [
│             "332"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Mon, 12 Aug 2024 09:05:43 GMT"
│         ],
│         "Etag": [
│             "W/\"14c-cIdKeGbJzW1WQ5QmgX8d9WiC9iU\""
│         ],
│         "Expires": [
│             "Mon, 12 Aug 2024 09:05:43 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "istio-envoy"
│         ],
│         "Set-Cookie": [
```

2024-08-12 09:35 UTC, iamar7 commented
Ran the command with the created resource group -> `ibmcloud resource service-instances --type all -g <resource-group>` and found that the COS is still not destroyed.

2024-08-13 15:08 UTC, iamar7 commented
/run pipeline

2024-08-15 10:54 UTC, ocofaigh requested changes
Left some comments. We need to do a better job with some of those variables descrptions, so adding Allen as reviewer for that.
Can you also fix the indendation in `stack_definition.json` so its consistent? 
FYI all default values being set in `stack_definition.json` get override with the default values your setting in `ibm_catalog.json` (as your code has mismatched values between them)

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"default_value": "__NULL__",
this should default to `private`. You should also customise it so its a dropdown box with 2 supported valued, private and public

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "The endpoint type to use if existing_secrets_manager_crn is specified.",
wrap existing_secrets_manager_crn in backticks -> `existing_secrets_manager_crn`

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "Cloud Internet Service ID.",
Needs a batter description - its required only when `secret_manager_public_engine_enabled` is true right? And is it always required when `secret_manager_public_engine_enabled` is true?

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "The name of the certificate authority for Secrets Manager.",
Again needs better description here - its required when `secret_manager_public_engine_enabled` is true right?

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"default_value": "certificate-dns",
Will this be different for every consumer? Should we even have a default value here (cc @alex-reiff )

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"required": false
This needs to be marked as sensitive

2024-08-15 10:54 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "The private key generated by the ACME account creation tool.",
Needs a better description - is is always required when `secret_manager_public_engine_enabled` is true?

2024-08-15 10:54 UTC, ocofaigh commented on stack_definition.json
> +		"default": "__NULL__",
should have default value of `private`

2024-08-15 10:54 UTC, ocofaigh commented on tests/pr_test.go
> +	acme_letsencrypt_private_key := GetSecretsManagerKey( // pragma: allowlist secret
your duplicating this in both tests - why not make it global and remove the duplication?

2024-08-15 18:16 UTC, SirSpidey requested changes
some suggestions and comments

2024-08-15 18:16 UTC, SirSpidey commented on ibm_catalog.json
> +							"description": "The private key generated by the ACME account creation tool.",
do client in the Cloud catalog know what the ACME tool is? If not, add
> For more information, see... and use a markdown link (`[]()`) to a doc topic about the tool.

2024-08-21 13:02 UTC, iamar7 commented
/run pipeline

2024-08-23 14:11 UTC, iamar7 commented on ibm_catalog.json
> +							"description": "Cloud Internet Service ID.",
It is CRN of the Cloud Internet Service instance. For more details -> https://cloud.ibm.com/catalog/services/internet-services

2024-08-23 14:24 UTC, iamar7 commented on ibm_catalog.json
> +							"default_value": "certificate-dns",
I have updated the default to be `null`

2024-08-23 14:27 UTC, iamar7 commented
/run pipeline

2024-08-26 06:34 UTC, iamar7 commented
/run pipeline

2024-08-26 14:50 UTC, SirSpidey approved these changes
Looks ok to me. Conall should review for whether it meets his earlier objections.

2024-08-26 14:50 UTC, SirSpidey commented on ibm_catalog.json
> +							"description": "The private key generated by the ACME account creation tool. For more information, see [documentation](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-prepare-
```suggestion
							"description": "The private key generated by the ACME protocol. For more information, see [Preparing to order public certificates](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-prepare-order-certificates).",
```

The docs refer to it as a protocol instead of a tool, so suggesting that here.

2024-08-26 14:51 UTC, SirSpidey commented
@iamar7 I approved, but I do have one suggestion.

2024-08-26 17:54 UTC, iamar7 commented
/run pipeline

2024-09-03 08:57 UTC, iamar7 commented
/run pipeline

2024-09-03 09:13 UTC, ocofaigh commented
@iamar7 The tests are blocked in this repo due to https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5586
We can add a workaround however we are expecting a fix from the provider soon, so going to wait for that.
This feature is not a high priority so it can wait until after the fix is in.
We already document how consumers can workaround the issue: https://cloud.ibm.com/docs/security-services?topic=security-services-known-issues#ki-scc-attachments

2024-09-12 13:22 UTC, ocofaigh commented
FYI, the pipeline is unblocked here

2024-09-13 05:50 UTC, iamar7 commented
/run pipeline

2024-09-13 06:07 UTC, iamar7 commented
/run pipeline

2024-09-16 11:53 UTC, closed without merging

2024-09-16 11:53 UTC, ocofaigh commented
As discussed internally, we are not going to expose all these new variables, but instead document how a user can achieve this by directly update the secrets manager member DA inside the stack.

I think that documentation would live in https://cloud.ibm.com/docs/security-services?topic=security-services-css-relnotes somewhere, so please work with @SirSpidey on that. Since there is no code changes needed in the repo, I'm going to close this PR.