feat: add cloud logs support
terraform-ibm-modules/stack-ibm-core-security-services pull request #141
Opened 2024-09-25 12:20 UTC by iamar7

### Description

Resolves: https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/115

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-09-25 12:20 UTC, iamar7 commented
/run pipeline

2024-09-25 14:41 UTC, iamar7 commented
/run pipeline

2024-09-26 16:00 UTC, ocofaigh requested changes
- You need to rename `enable_platform_logs_metrics` to `enable_platform_metrics` since we will no longer provision Log Analysis. To enable platform logs with cloud logs, users will not use the new `logs_routing_tenant_regions` input.
- There is now a circular dependency you need to resolve - removed `existing_monitoring_crn` from Event Notifications input (line 239). The dependency is now the other way around - Observability depends on EN.

2024-09-26 16:00 UTC, ocofaigh commented on stack_definition.json
> +          "value": "ref:../../inputs/existing_en_instance_crn"
thats not right - the ref needs to come from the Event Notifications DA output

2024-09-27 07:09 UTC, iamar7 commented
/run pipeline

2024-09-27 11:34 UTC, iamar7 commented
Getting this in the pipeline.
> Error: ServiceNotAuthorized: The specified COS Service Instance does not have sufficient permissions to access the resource associated with the KMS key CRN.
>  2024/09/27 11:26:44 Terraform apply | 	status code: 401, request id: 2741b9da-xxxd-4xx2-bxxa-b5xxxxxXXxxxxdbdf, host id: 
>  2024/09/27 11:26:44 Terraform apply | 
>  2024/09/27 11:26:44 Terraform apply |   with module.cos[0].ibm_cos_bucket.cos_bucket[0],
>  2024/09/27 11:26:44 Terraform apply |   on .terraform/modules/cos/main.tf line 133, in resource "ibm_cos_bucket" "cos_bucket":
>  2024/09/27 11:26:44 Terraform apply |  133: resource "ibm_cos_bucket" "cos_bucket" {

2024-10-01 13:24 UTC, iamar7 commented
/run pipeline

2024-10-01 14:35 UTC, ocofaigh requested changes
You can keep `enable_platform_logs_metrics` instead of splitting into 2 separate ones

2024-10-01 15:49 UTC, iamar7 commented
/run pipeline

2024-10-02 22:47 UTC, iamar7 commented
/run pipeline

2024-10-03 07:25 UTC, iamar7 commented
Getting this in the pipeline run -

![Screenshot 2024-10-03 at 6 16 42 AM](https://github.com/user-attachments/assets/3123ee59-57b5-4734-9810-0605afd6fb8f)

2024-10-03 08:25 UTC, ocofaigh commented
@iamar7 Can we update all of the version locators to match what we have in the RAG stack: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/main/solutions/basic/stack_definition.json

At least we know that exact combination works. Keep on eye on some of the member inputs and refs, as they may need updates too.

2024-10-03 10:52 UTC, iamar7 commented
/run pipeline

2024-10-03 14:54 UTC, iamar7 commented
/run pipeline

2024-10-04 10:54 UTC, ocofaigh commented
/run pipeline

2024-10-04 12:19 UTC, iamar7 commented
@ocofaigh The pipeline is failing is due to the changes in order of `observability` and `event notification`. Earlier, the `cos_kms_auth_policy` was being created in the observability-da and skipped in the event-notification DA. So now since the event notification DA is being deployed first so need to create the `cos_kms_auth_policy` in the `event-notification DA` and skip it in the observability-da.

2024-10-04 12:30 UTC, iamar7 commented
/run pipeline

2024-10-04 12:56 UTC, ocofaigh commented
I think we will want to do a manual upgrade test against this branch before we proceed - but lets get pipeline passing here fist and ill get prepped for a manual upgrade

2024-10-04 15:17 UTC, iamar7 commented
`TestProjectsFullTest` passed in the above run.

2024-10-07 08:38 UTC, ocofaigh commented
As discussed internally, there is a breaking change here due to the dependency tree order changing and the requirement to change which DA is creating the COS to KMS auth policy. We are discussing options currently.

2024-10-07 11:07 UTC, ocofaigh requested changes
@iamar7 While we are making a decision on how to handle the breaking change, can you please update the diagram to replace Log Analysis with Cloud Logs, the cloud logs bucket, and the AT route to cloud logs

2024-10-07 12:07 UTC, iamar7 commented
> @iamar7 While we are making a decision on how to handle the breaking change, can you please update the diagram to replace Log Analysis with Cloud Logs, the cloud logs bucket, and the AT route to cloud logs

Sure @ocofaigh

2024-10-07 16:51 UTC, ocofaigh commented on stack_definition.json
> -          "value": "ref:../../members/2 - Observability/outputs/cloud_monitoring_crn"
FYI, I found another projects [bug](https://github.ibm.com/epx/projects/issues/3646) where projects is not removing this value from the stack on upgrade. So for now, I think we need to workaround it by explicitly passing `__NULL__` here. I'm going to push a commit and try it out.

2024-10-08 09:01 UTC, ocofaigh commented
There is another issue we are seeing now when upgrading Observability to remove logdna:
```
 2024/10/08 07:47:24 Terraform plan | Error: Cannot read the remote archive resource
 2024/10/08 07:47:24 Terraform plan | 
 2024/10/08 07:47:24 Terraform plan |   with module.observability_instance.module.log_analysis[0].logdna_archive.archive_config[0],
 2024/10/08 07:47:24 Terraform plan |   on .terraform/modules/observability_instance/modules/log_analysis/main.tf line 42, in resource "logdna_archive" "archive_config":
 2024/10/08 07:47:24 Terraform plan |   42: resource "logdna_archive" "archive_config" {
 2024/10/08 07:47:24 Terraform plan | 
 2024/10/08 07:47:24 Terraform plan | expected either servicekey or iamtoken to be set
```

My guess is since we have identified the logdna resources (including the resource key used to initialise the logdna provider) for deletion, the logdna provider can no longer be initialised, and we get this error.
We need to find a way to handle this.

2024-10-11 09:31 UTC, ocofaigh commented
Going to have to do the upgrade in a 2 step process to fully removed Log Analysis. In this PR we will disable the log archiving, but keep the LogDNA instance up, as well as deploy Cloud Logs. We will deploy Cloud Logs without Event Notifications integration for now, and in the next release, we will add it, since it will require manual steps to upgrade, so hence will make the next change a major version update.

2024-10-11 09:31 UTC, ocofaigh commented
/run pipeline

2024-10-11 10:59 UTC, ocofaigh commented
Some issue with key protect service:
```
 2024/10/11 10:05:51 Terraform apply | ---
 2024/10/11 10:05:51 Terraform apply | id: terraform-46882f4c
Error: 0/11 10:05:51 Terraform apply | summary: '[ERROR] Error while creating key ring : kp.Error:
 2024/10/11 10:05:51 Terraform apply | correlation_id=''7c640068-1d71-4343-859f-99bbe462ece7'',
 2024/10/11 10:05:51 Terraform apply |   msg=''This operation cannot be completed. Please try your request at a later time.
 2024/10/11 10:05:51 Terraform apply |   If the issue persists, please contact IBM KeyProtect.'''
 2024/10/11 10:05:51 Terraform apply | severity: error
 2024/10/11 10:05:51 Terraform apply | resource: ibm_kms_key_rings
 2024/10/11 10:05:51 Terraform apply | operation: create
 2024/10/11 10:05:51 Terraform apply | component:
 2024/10/11 10:05:51 Terraform apply |   name: github.com/IBM-Cloud/terraform-provider-ibm
 2024/10/11 10:05:51 Terraform apply |   version: 1.69.2
 2024/10/11 10:05:51 Terraform apply | ---
```

Retrying..

2024-10-11 11:00 UTC, ocofaigh commented
/run pipeline

2024-10-11 12:31 UTC, ocofaigh approved these changes

2024-10-11 12:31 UTC, merged

2024-10-11 12:32 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v1.5.0)
- `v1.5.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-11 14:30 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v1.5.0)
- `v1.5.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-11 18:10 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v1.5.0)
- `v1.5.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: