Update content
terraform-ibm-modules/stack-ibm-core-security-services pull request #20
Opened 2024-05-29 21:03 UTC by SirSpidey

### Description

Editorial review of content strings.

Make sure that these changes make sense in the stack context.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-31 10:30 UTC, ocofaigh requested changes
Thanks @SirSpidey - left some comments

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +			"long_description": "This architecture deploys the following core security services: Key Protect, Secrets Manager, and Security and Compliance Center. It also deploys Event Notifications and Obser
It also supports deploying the Security and Compliance Center Workload Protection instance

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +					"description": "Creates and configures an IBM Key Protect instance and creates root keys for IBM Cloud Object Storage and Secrets Manager."
root key also created for Event Notifications

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +					"description": "Creates and configures an IBM Security Compliance Center instance."
Maybe we need a new title for Security and Compliance Center Workload Protection instance ?

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +					"description": "Creates and configures service-to-service authorizations for the following services: KMS, Object Storage, Secrets Manager, and Security and Compliance Center."
Event Notifications too

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +								"description": "Creates and configures an IBM Key Protect instance and creates root keys for Secret Manager and IBM Cloud Object Storage."
root key also created for Event Notifications

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +								"description": "Creates and configures an IBM Security Compliance Center instance."
Maybe we need a new title for Security and Compliance Center Workload Protection instance ?

2024-05-31 10:30 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "The pricing plan to use for the Secrets Manager deployable architecture.",
hmm, maybe don't say `deployable architecture` - some day it may come from module registry

2024-05-31 18:26 UTC, SirSpidey commented on ibm_catalog.json
> +					"description": "Creates and configures an IBM Security Compliance Center instance."
Added a feature for WP

2024-05-31 18:28 UTC, SirSpidey commented on ibm_catalog.json
> +								"description": "Creates and configures an IBM Security Compliance Center instance."
Added a feature for WP

2024-05-31 18:30 UTC, SirSpidey commented on ibm_catalog.json
> +							"description": "The pricing plan to use for the Secrets Manager deployable architecture.",
shortened just to `for Secrets Manager`, assuming that makes sense in this context.

2024-05-31 18:31 UTC, SirSpidey commented
@ocofaigh updated based on your review. The feature descriptions aren't the most useful -- they really just add extra words to the title. But I have left them as is for the time being.

2024-06-03 18:33 UTC, ocofaigh commented
/run pipeline

2024-06-03 18:43 UTC, ocofaigh approved these changes

2024-06-03 18:44 UTC, merged