Create reference-architecture-css.md
terraform-ibm-modules/stack-ibm-core-security-services pull request #35
Opened 2024-06-12 21:14 UTC by joealewine

### Description

Add reference architecture doc to CSS DA repo.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-12 21:28 UTC, SirSpidey approved these changes
So you can get this out, I didn't do a re-review of the earlier content in landing zone

2024-06-12 21:28 UTC, SirSpidey submitted a review, later dismissed

2024-06-12 21:28 UTC, SirSpidey commented
/run pipeline

2024-06-12 21:49 UTC, bhakta-ibm commented on reference-architecture/reference-architecture-css.md
> +![heatmap](heat-map-ccs.svg "Current diagram"){: caption="Figure 2. Architecture design scope" caption-side="bottom"}
You didn't include the heatmap image as part of PR, it was included in my zip.

2024-06-13 13:22 UTC, SirSpidey commented
@joealewine Another issue I missed: directory needs to be plural: `/reference architectures/`

2024-06-13 16:35 UTC, SirSpidey approved these changes
Things look like they're in the right places now. 👍

2024-06-13 16:36 UTC, SirSpidey commented
@joealewine After you resolve the conflict with the `core-security-services-architecture.svg` file, we can probably get it merged.

2024-06-13 19:00 UTC, SirSpidey commented
/run pipeline

2024-06-13 19:00 UTC, SirSpidey submitted a review, later dismissed
🐎

2024-06-13 19:18 UTC, SirSpidey commented
/run pipeline

2024-06-13 19:30 UTC, SirSpidey commented
/run pipeline

2024-06-13 19:47 UTC, SirSpidey submitted a review, later dismissed
re-approving

2024-06-13 19:59 UTC, bhakta-ibm submitted a review, later dismissed
lgtm

2024-06-14 11:32 UTC, bhakta-ibm commented
@ocofaigh can you please merge this?

2024-06-14 11:57 UTC, ocofaigh requested changes
@bhakta-ibm The diagram was recently updated to include COS bucket support for event notifications - it seems the diagram in this PR does not have that

2024-06-14 12:18 UTC, bhakta-ibm commented
The PR should just have reference to that diagram should not replace it. So not sure the diagram is commited.

2024-06-14 12:44 UTC, SirSpidey commented
> The PR should just have reference to that diagram should not replace it. So not sure the diagram is commited.

@bhakta-ibm Just heard from Conall, so I think you are working on this. But the background is that the directory needs to be plural for the cloud docs jobs (`reference architectures`), so the new diagram probably needs to be renamed/added to the PR.

2024-06-14 12:50 UTC, bhakta-ibm commented
> > The PR should just have reference to that diagram should not replace it. So not sure the diagram is commited.
> 
> @bhakta-ibm Just heard from Conall, so I think you are working on this. But the background is that the directory needs to be plural for the cloud docs jobs (`reference architectures`), so the new diagram probably needs to be renamed/added to the PR.

@joealewine is on it, the branch is on his fork so couldn't make the change.

2024-06-14 13:20 UTC, joealewine commented
@bhakta-ibm @ocofaigh Ok I think I've got it fixed now (or rather, just renamed, so the file is the same as it was in the main branch)

2024-06-14 13:32 UTC, daniel-butler-irl commented
/run pipeline

2024-06-14 13:32 UTC, ocofaigh approved these changes

2024-06-14 13:37 UTC, ocofaigh requested changes
You need to remove this file from the PR:
```
Forbid binaries...........................................................Failed
- hook id: forbid-binary
- exit code: 1

Error:  .DS_Store appears to be a binary file
```

Would you be able to add it to the .gitignore file to ensure it can't be committed in the future?

2024-06-14 13:40 UTC, SirSpidey commented
> Would you be able to add it to the .gitignore file to ensure it can't be committed in the future?

@joealewine We have these instructions for ignoring .DS_STORE files: [Macs only: Ignoring .DS_Store files](https://test.cloud.ibm.com/docs-internal/writing?topic=writing-setting-up-your-markdown-environment#ignore-ds_store)

2024-06-14 13:55 UTC, joealewine commented
I will not be adding it to gitignore. Every time I touch something in this PR something else seems to break. So I'll let one of you do that. I just want this thing merged so I can link to it from other docs. That's it

2024-06-14 13:58 UTC, daniel-butler-irl commented
/run pipeline

2024-06-14 14:16 UTC, bhakta-ibm approved these changes
lgtm

2024-06-14 14:37 UTC, ocofaigh approved these changes

2024-06-14 14:37 UTC, merged

2024-06-14 15:12 UTC, hvetsa commented
> I will not be adding it to gitignore. Every time I touch something in this PR something else seems to break. So I'll let one of you do that. I just want this thing merged so I can link to it from other docs. That's it

I agree, we are holding a lot of updates for next revisions. Let us push these into repo and address next set of changes in another PR.

2024-06-18 12:07 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.2.1 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v0.2.1)
- `v0.2.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: