feat: add outputs of services:
terraform-ibm-modules/stack-ibm-core-security-services pull request #52
Opened 2024-06-19 21:02 UTC by jor2

### Description

add outputs of services

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-19 21:03 UTC, jor2 commented on stack_definition.json
> -					"value": "true"
should this be a string?

2024-06-19 21:03 UTC, jor2 commented on stack_definition.json
> -					"name": "existing_en_crn",
value was passed twice to this DA.

2024-06-19 21:03 UTC, jor2 commented
/run pipeline

2024-06-20 08:14 UTC, ocofaigh requested changes
see comments

2024-06-20 08:14 UTC, ocofaigh commented on ibm_catalog.json
> +							"description": "The CRN of the Key Protect instance."
This may not be Key Protect though, because user could supply an existing HPCS instance using the variable `existing_kms_instance_crn`. So use the string "key management service instance" instead

2024-06-20 08:14 UTC, ocofaigh commented on ibm_catalog.json
> +						}
its missing SCC workload protection instance CRN, the COS instance CRN, and the logging CRN

2024-06-20 08:14 UTC, ocofaigh commented on stack_definition.json
> -					"value": "true"
I think in the end terraform converts it to a bool if the variable is a bool, but better to have it bool here like you updated to

2024-06-20 10:19 UTC, jor2 commented on ibm_catalog.json
> +						}
cos is there

2024-06-20 11:21 UTC, ocofaigh approved these changes

2024-06-20 11:21 UTC, ocofaigh commented
/run pipeline

2024-06-20 13:21 UTC, ocofaigh approved these changes

2024-06-20 13:21 UTC, merged

2024-06-20 13:22 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.6.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v0.6.0)
- `v0.6.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: