feat: support for existing kms instance
terraform-ibm-modules/stack-ibm-core-security-services pull request #64
Opened 2024-06-24 09:44 UTC by Soaib024

### Description

- [#77](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/77) Added support for existing kms instance
- [#55](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/55) Added new PR test with existing kms and sm instance

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added support for existing kms instance

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-24 09:45 UTC, Soaib024 commented
/run pipeline

2024-06-24 09:49 UTC, Soaib024 commented
/run pipeline

2024-06-24 11:06 UTC, Soaib024 commented
Successfully deployed with existing HPCS `geretain-hyper-protect-crypto-us-south` present in ge-dev account

<img width="1728" alt="Screenshot 2024-06-24 at 2 41 52 PM" src="https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/33781996/46fd77f4-757d-473f-8851-f2a73ce0852d">

<img width="1728" alt="Screenshot 2024-06-24 at 2 42 08 PM" src="https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/33781996/6a067097-7def-457d-9ab6-7bffbbd5ef30">

2024-06-24 12:08 UTC, Soaib024 commented
/run pipeline

2024-06-24 13:19 UTC, Soaib024 commented
/run pipeline

2024-06-24 13:24 UTC, ocofaigh commented on tests/pr_test.go
> +		"sm_service_plan":              "trial",
lets use existing secrets manager too

2024-06-24 13:25 UTC, ocofaigh commented on tests/pr_test.go
> +		"sm_service_plan":              "trial",
ah wait you already have it. So no need to set any value for `sm_service_plan` here - it wont be used

2024-06-24 13:29 UTC, Soaib024 commented on tests/pr_test.go
> +		"sm_service_plan":              "trial",
removed

2024-06-24 13:29 UTC, Soaib024 commented
/run pipeline

2024-06-25 06:02 UTC, Soaib024 commented
/run pipeline

2024-06-26 09:22 UTC, Soaib024 commented
/run pipeline

2024-07-01 09:34 UTC, Soaib024 commented
/run pipeline

2024-07-04 06:08 UTC, Soaib024 commented
/run pipeline

2024-07-04 07:24 UTC, Soaib024 commented
/run pipeline

2024-07-04 08:02 UTC, ocofaigh commented on tests/pr_test.go
> +	t.Skip()
why is this being skipped?

2024-07-04 08:18 UTC, Soaib024 commented on tests/pr_test.go
> +	t.Skip()
That was just for testing. I have removed the skip statement but commented out the section where we pass the existing secrets manager due to the [issue](https://github.ibm.com/GoldenEye/issues/issues/9709#issuecomment-83874969). I will uncomment it when we have the fix.

issue for the fix: https://github.ibm.com/GoldenEye/issues/issues/9296

2024-07-04 08:20 UTC, Soaib024 commented
/run pipeline

2024-07-04 14:55 UTC, Soaib024 commented
/run pipeline

2024-07-04 16:31 UTC, ocofaigh requested changes
1 minor comment

2024-07-04 16:31 UTC, ocofaigh commented on tests/pr_test.go
> +		// "existing_secrets_manager_crn": permanentResources["secretsManagerCRN"],
since your not using existiing SM, you should set `"sm_service_plan": "trial",` so we don't provision expensive standard instances in every PR

2024-07-04 16:41 UTC, Soaib024 commented on tests/pr_test.go
> +		// "existing_secrets_manager_crn": permanentResources["secretsManagerCRN"],
added

2024-07-04 16:41 UTC, Soaib024 commented
/run pipeline

2024-07-04 16:42 UTC, ocofaigh approved these changes

2024-07-05 08:34 UTC, merged

2024-07-05 08:35 UTC, terraform-ibm-modules-ops commented
:tada: This issue has been resolved in version 1.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v1.2.0)
- `v1.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: