fix: adding iam_engine_enabled option
terraform-ibm-modules/stack-ibm-core-security-services pull request #70
Opened 2024-06-27 09:07 UTC by iamar7

### Description

Resolves: https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/59

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-27 12:28 UTC, iamar7 commented
/run pipeline

2024-07-01 10:00 UTC, iamar7 commented
/run pipeline

2024-07-01 11:51 UTC, iamar7 commented
/run pipeline

2024-07-01 15:57 UTC, iamar7 commented
/run pipeline

2024-07-02 09:13 UTC, ocofaigh requested changes
some further suggestions

2024-07-02 09:13 UTC, ocofaigh commented on ibm_catalog.json
> +							"key": "iam_engine_enabled",
I suggest to update this to `secret_manager_iam_engine_enabled`

2024-07-02 09:13 UTC, ocofaigh commented on stack_definition.json
> +			"name": "iam_engine_enabled",
I suggest to update this to `secret_manager_iam_engine_enabled`

2024-07-02 09:13 UTC, ocofaigh commented on stack_definition.json
> +					"value": "ref:../../inputs/iam_engine_enabled"
I suggest to update this to `ref:../../inputs/iam_engine_enabled/secret_manager_iam_engine_enabled`

2024-07-04 13:06 UTC, iamar7 commented
/run pipeline

2024-07-04 13:36 UTC, ocofaigh requested changes
I see you updated all the icons in the diagram except the event notifications one - can we be consistent and update the one too?

2024-07-04 13:57 UTC, iamar7 commented
> n we be consistent and



> I see you updated all the icons in the diagram except the event notifications one - can we be consistent and update the one too?

Can you tell me which icon to use for event notification as I see the same icon being used [here](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/blob/main/reference-architectures/en.svg) in the event-notification DA reference-architecture.

2024-07-04 16:33 UTC, ocofaigh commented
@iamar7 No idea - where did you get the other icons from? Maybe check with people who worked on the other DA diagrams

2024-07-05 09:26 UTC, iamar7 commented
> @iamar7 No idea - where did you get the other icons from? Maybe check with people who worked on the other DA diagrams

I've used the icons from ibm-cloud stencils repo [here](https://github.ibm.com/ibmcloud/ibm-cloud-stencils#importing-stencil-libraries-into-drawio).

2024-07-05 14:15 UTC, iamar7 commented
> @iamar7 No idea - where did you get the other icons from? Maybe check with people who worked on the other DA diagrams

I asked about the icon in the IBM Cloud Stencils [channel](https://ibm-cloudplatform.slack.com/archives/C010ARBDZ9R/p1720173347984069), and they confirmed that it is not available in the current library. I have created an [issue](https://github.ibm.com/ibmcloud/ibm-cloud-stencils/issues/158) for further tracking.

2024-07-05 14:15 UTC, iamar7 commented
/run pipeline

2024-07-10 06:55 UTC, iamar7 commented
/run pipeline

2024-07-15 17:31 UTC, iamar7 commented
/run pipeline

2024-07-16 12:17 UTC, iamar7 commented
/run pipeline

2024-07-26 09:27 UTC, ocofaigh commented
Blocked by known issue with the tests which is being debugged internally

2024-07-29 10:28 UTC, iamar7 commented
/run pipeline

2024-07-29 10:58 UTC, iamar7 commented
/run pipeline

2024-07-29 13:18 UTC, ocofaigh requested changes
1 comment

2024-07-29 13:18 UTC, ocofaigh commented on tests/pr_test.go
> +		"secret_manager_iam_engine_enabled": true,
To be safe, I think set this to false for now. The reason being that under this we have `existing_secrets_manager_crn` commented out. If some create a PR to add that back in, its going to try and enable the IAM engine on our existing SM instance, and it may break (or fail). We are testing the IAM engine creation in the `TestProjectsFullTest` so there is no test gap by setting this to false

2024-07-29 13:20 UTC, iamar7 commented
/run pipeline

2024-07-29 15:02 UTC, merged

2024-07-29 15:03 UTC, terraform-ibm-modules-ops commented
:tada: This issue has been resolved in version 1.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/releases/tag/v1.3.0)
- `v1.3.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: