First Version
terraform-ibm-modules/stack-ibm-core-security-services pull request #8
Opened 2024-05-15 19:30 UTC by tyao117

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-16 13:32 UTC, ocofaigh requested changes
@tyao117 left some comments

2024-05-16 13:32 UTC, ocofaigh commented on stack_definition.json
> +				{
your missing input `existing_event_notification_instance_crn` which should come from EN output

2024-05-16 13:32 UTC, ocofaigh commented on stack_definition.json
> +			"inputs": [
since you are going to create COS with Observability DA, maybe you should set the value of `cos_instance_name` in here because other wise it will be called `"observability-cos"` however this COs will be used for more than just Observability

2024-05-16 13:32 UTC, ocofaigh commented on stack_definition.json
> +	"inputs": [
I suggest exposing SM plan at the top level stack as input so people can choose trial or standard (we will want to use trial for our internal testing due to cost)

2024-05-17 14:29 UTC, ccmitchellusa commented
In stack_definition.json member for `2a - Security Service - Key Management", there are two inputs with the same name, "region".

2024-05-17 19:07 UTC, tyao117 commented on ibm_catalog.json
> +								"names": [
i did pass the full profile last time i imported it, but it would not allow me to pass validation on the private catalog validation portion.

All controls in the profile need to pass or it won't allow a release.

2024-05-17 19:42 UTC, tyao117 commented on ibm_catalog.json
> +								"diagram": {
I believe @bhakta-ibm has a PR that needs to be approved first containing the diagram

2024-05-20 08:40 UTC, ocofaigh commented on ibm_catalog.json
> +			"version": "0.0.1",
@tyao117 this still needs to be addressed

2024-05-20 08:42 UTC, ocofaigh commented on ibm_catalog.json
> +			"offering_icon_url": "https://globalcatalog.cloud.ibm.com/api/v1/1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc/artifacts/terraform.svg",
tracking in https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/14

2024-05-20 08:42 UTC, ocofaigh commented on ibm_catalog.json
> +			"provider_name": "Community",
This should be IBM not Community

2024-05-20 08:44 UTC, ocofaigh commented on ibm_catalog.json
> +								"names": [
This is not true - you can pass a full profile (like they did in RAG stack [here](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/2bc15101e8cb06009715fc6ce153b76565414e3d/ibm_catalog.json#L49-L57)) and when you attach and SCC scan with all resources that were deployed as part of validation, catalog will only claim the passing controls

2024-05-20 08:48 UTC, ocofaigh commented on ibm_catalog.json
> +								"diagram": {
tracking at https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/15

2024-05-20 08:51 UTC, ocofaigh commented
@tyao117 just a final few comments, and I think we should merge and get 0.0.1 release out for initial testing and feedback

2024-05-20 08:53 UTC, ocofaigh requested changes
Oh actually @tyao117 can we also use numbering for the stack member names so they get ordered in the order they need to be deployed? Same way they did it for RAG stack

2024-05-20 12:07 UTC, daniel-butler-irl commented on stack_definition.json
> +			"name": "scc_service_plan",
This is a duplicate of the below and has a description for the default value. Remove this

2024-05-20 18:10 UTC, tyao117 commented on stack_definition.json
> +				{
https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/pull/8/files#diff-47513878fa1687ae846161d0fd5e96a62442127ddb151bd015cc9881b065144fR222

2024-05-20 18:16 UTC, ocofaigh commented on ibm_catalog.json
> +					"compliance": {
the syntax is slight different when claiming a full profile:
```
"compliance": {
              "authority": "scc-v3",
              "profiles": [
                {
                  "profile_name": "CIS IBM Cloud Foundations Benchmark",
                  "profile_version": "1.0.0"
                }
              ]
            },
```

2024-05-20 18:26 UTC, tyao117 commented on stack_definition.json
> +			"inputs": [
https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/pull/8/files#diff-47513878fa1687ae846161d0fd5e96a62442127ddb151bd015cc9881b065144fR97

2024-05-20 18:26 UTC, tyao117 commented on stack_definition.json
> +			"name": "scc_service_plan",
already removed.

2024-05-20 18:27 UTC, daniel-butler-irl commented
@tyao117 I pushed a working simple test for you. I just validates the stack deploys successfully. @ocofaigh FYI

2024-05-20 18:28 UTC, daniel-butler-irl commented
/run pipeline

2024-05-20 19:04 UTC, daniel-butler-irl commented
Some inputs do not match what the current DAs expect:
![image](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/10742925/45c3c060-bab9-4df2-8e7c-12bc88bf5cab)
![image](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/10742925/2ebfba8e-7592-408f-9d7b-586cd645a800)

I think in `4a - core-security-services-scc`   
`existing_en_instance_crn` - >`existing_en_crn`
`region` -> `scc_region`

2024-05-20 19:05 UTC, daniel-butler-irl commented
/run pipeline

2024-05-20 19:08 UTC, daniel-butler-irl commented
/run pipeline

2024-05-20 19:31 UTC, ocofaigh commented
@daniel-butler-irl Does the stack have to exist in a catalog or something for tests to work? Its currently failing with `Error creating config from JSON: Error retrieving from catalog: Catalog &quot;7df1e4ca-d54c-4fd0-82ce-3d13247308cd&quot; not found in account &quot;abac0df06b644a9cabc6e44f55b3880e&quot;`

2024-05-20 19:36 UTC, ocofaigh commented
Ah the version locators might need to be updated to pull from Community registry, and thats why test is failing in DEDev account

2024-05-20 20:12 UTC, tyao117 commented
/run pipeline

2024-05-20 20:39 UTC, tyao117 commented
/run pipeline

2024-05-20 20:54 UTC, tyao117 commented
/run pipeline

2024-05-22 11:59 UTC, daniel-butler-irl commented
/run pipeline

2024-05-24 11:58 UTC, daniel-butler-irl commented
/run pipeline

2024-05-24 13:15 UTC, ocofaigh approved these changes

2024-05-24 13:15 UTC, merged